name: PHPStan

on:
  push:
    paths:
      - '**.php'
      - phpstan.neon
      - .github/workflows/phpstan.yml

permissions:
  contents: read

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Install Composer Dependencies
        uses: ramsey/composer-install@v4

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
